spring.application.name=Backend

# API Keys
maptiler.api.key=${MAPTILER_API_KEY}

geoapify.api.key=${GEOAPIFY_API_KEY}

jwt.secret=${JWT_SECRET}

# Database
spring.datasource.url=${SPRING_DATASOURCE_URL}

spring.datasource.username=${SPRING_DATASOURCE_USERNAME}

spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate=DEBUG
logging.level.org.springframework.orm.jpa=DEBUG

# PostgreSQL Dialect
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Server
server.port=${PORT:8080}

# Mail
spring.mail.host=smtp.gmail.com
spring.mail.port=465
spring.mail.username=${MAIL_USERNAME}

spring.mail.password=${MAIL_PASSWORD}

spring.mail.protocol=smtps
spring.mail.properties.mail.smtps.auth=true
spring.mail.properties.mail.smtps.ssl.enable=true
spring.mail.properties.mail.smtps.starttls.enable=false
spring.mail.properties.mail.smtps.ssl.trust=smtp.gmail.com
spring.mail.properties.mail.smtps.connectiontimeout=15000
spring.mail.properties.mail.smtps.timeout=15000
spring.mail.properties.mail.smtps.writetimeout=15000