spring.application.name=Backend

maptiler.api.key=03OjfPEHqGebQmrx2SOK
geoapify.api.key=f42ea210f5c8455b9b21585bfaaf3c97
# Oracle Database
spring.datasource.url=jdbc:oracle:thin:@localhost:1521/XEPDB1
spring.datasource.username=herguardian
spring.datasource.password=hg123
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate=DEBUG
logging.level.org.springframework.orm.jpa=DEBUG

# Oracle Dialect
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect

# Server
server.port=8080

# Mail (we'll configure later)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=leelasatyavijayeswari1022@gmail.com
spring.mail.password=akptzlxsrgpzfhib
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

spring.mail.properties.mail.smtp.connectiontimeout=10000
spring.mail.properties.mail.smtp.timeout=10000
spring.mail.properties.mail.smtp.writetimeout=10000